[package]
name = "rust-empty-firmware-template"
version = "0.1.0"
edition = "2024"

[dependencies]
stm32f4 = { version = "0.15.0", features = ["stm32f411", "rt"] }
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"