[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
linker = "arm-none-eabi-ld"
runner = "probe-run --chip STM32F411RE"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=--nmagic"
]

[unstable]
build-std = ["core"]