[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "arm-none-eabi-ld"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=--nmagic"
]
runner = "probe-rs run --chip STM32F411RE"

[unstable]
build-std = ["core"]